import { Roboto } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Title from "./Title";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--roboto",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.className}`}>
      <body className="mx-8 mt-8">
        <Title />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
